import { getSignedUploadUrl, deleteFile } from "@/app/actions/storage";
import { s3Config } from "./s3-client";

export interface UploadResult {
  url: string;
  path: string;
  error?: string;
}

export interface UploadOptions {
  bucket?: string;
  folder?: string;
  maxSizeInMB?: number;
  allowedTypes?: string[];
}

const DEFAULT_OPTIONS: UploadOptions = {
  bucket: s3Config.bucket,
  folder: "uploads",
  maxSizeInMB: 5,
  allowedTypes: [
    "image/jpeg",
    "image/jpg",
    "image/png",
    "image/webp",
    "image/gif",
  ],
};

/**
 * Validates a file before upload
 */
export function validateFile(
  file: File,
  options: UploadOptions = {}
): { valid: boolean; error?: string } {
  const opts = { ...DEFAULT_OPTIONS, ...options };

  // Check file type
  if (opts.allowedTypes && !opts.allowedTypes.includes(file.type)) {
    return {
      valid: false,
      error: `Invalid file type. Allowed types: ${opts.allowedTypes.join(
        ", "
      )}`,
    };
  }

  // Check file size
  const maxSizeInBytes = (opts.maxSizeInMB || 5) * 1024 * 1024;
  if (file.size > maxSizeInBytes) {
    return {
      valid: false,
      error: `File size exceeds ${opts.maxSizeInMB}MB limit`,
    };
  }

  return { valid: true };
}

/**
 * Uploads a file to S3 using presigned URL generated by server action
 */
export async function uploadImage(
  file: File,
  options: UploadOptions = {}
): Promise<UploadResult> {
  const opts = { ...DEFAULT_OPTIONS, ...options };

  // Validate file
  const validation = validateFile(file, opts);
  if (!validation.valid) {
    return { url: "", path: "", error: validation.error };
  }

  try {
    // Generate unique filename
    const fileExt = file.name.split(".").pop();
    const fileName = `${Date.now()}-${Math.random()
      .toString(36)
      .substring(7)}.${fileExt}`;

    // Get presigned URL from server action
    const { success, signedUrl, publicUrl, filePath, error } =
      await getSignedUploadUrl(file.type, fileName, opts.folder);

    if (!success || !signedUrl || !publicUrl || !filePath) {
      throw new Error(error || "Failed to get upload URL");
    }

    // Upload file to S3 using presigned URL
    const uploadResponse = await fetch(signedUrl, {
      method: "PUT",
      body: file,
      headers: {
        "Content-Type": file.type,
      },
    });

    if (!uploadResponse.ok) {
      throw new Error(`Upload failed: ${uploadResponse.statusText}`);
    }

    return {
      url: publicUrl,
      path: filePath,
    };
  } catch (error) {
    console.error("Upload error:", error);

    let errorMessage = "Upload failed";

    if (error instanceof Error) {
      errorMessage = error.message;
    }

    return {
      url: "",
      path: "",
      error: errorMessage,
    };
  }
}

/**
 * Uploads multiple files to S3
 */
export async function uploadMultipleImages(
  files: File[],
  options: UploadOptions = {}
): Promise<UploadResult[]> {
  const uploadPromises = files.map((file) => uploadImage(file, options));
  return Promise.all(uploadPromises);
}

/**
 * Deletes a file from S3 using server action
 */
export async function deleteImage(
  path: string,
  _bucket?: string // parameter kept for compatibility but not used as server config decides bucket
): Promise<{ success: boolean; error?: string }> {
  const result = await deleteFile(path);
  return result;
}